module.exports = {
    cashloan: '现金借款',
    creditcard: '办信用卡',
    newsdetail: '新闻详情',
    qinbei: '亲呗',
    auditfail: '审核失败',
    creditfail: '授信失败',
    creditline: '授信额度',
    basicinfo: '基本信息',
    repayment: '还款中',
    repaymentlist: '还款列表',
    contract: '借款合同',
    myloan: '我的借款',
    loandetail: '借款详情',
    details: '资讯详情',
    userinfo: '基本信息',
    contactinfo: '联系人信息',
    crediting: '授信中',
    repaywhite: '待还款',
    payload: '还款中',
    repayresult: '还款成功',
    repayfail: '还款失败',
    runrepay: '立即还款',
    advance: '提前结清',
    loanapplication: '申请借款',
    refundplan: '还款计划',
    affirmborrow: '确认借款',
    makeioans: '放款中',
    tieCard: '绑卡',
    cardmange: '卡管理',
    helpcenter: '帮助中心',
    questions: '问题列表',
    qadetail: '问题详情',
    about: '关于我们',
    cashborrow: '现金借款'

};
// '联系客服为弹框，暂时放在全局组件里面',
